title: 李嘉鹏的主页
page-top-title: 李嘉鹏&ensp;|&ensp;LI Jia-Peng
top-section-bg-text: 月球开发 功在当代 利在千秋
home-subtitle: 李嘉鹏&ensp;|&ensp;LI Jia-Peng
copyright-text: '&copy; LI Jia-Peng 2025. All Rights Reserved.'