title: 李嘉鹏的主页
page-top-title: 李嘉鹏&ensp;|&ensp;LI Jia-Peng
top-section-bg-text: Boldly go where no one has gone before
home-subtitle: 李嘉鹏&ensp;|&ensp;LI Jia-Peng
copyright-text: '&copy; LI Jia-Peng 2025. All Rights Reserved.'